default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bt_movies_demo_development

test: &test
  <<: *default
  database: bt_movies_demo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: bt_movies_demo_production
